function Hd = cic1_gen
%CIC1_GEN Returns a multirate filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the DSP System Toolbox 8.0.
%
% Generated on: 25-Dec-2014 08:19:46
%

decf    = 6;  % Decimation Factor
diffd   = 1;  % Differential Delay
numsecs = 1;  % Number of Sections

Hd = mfilt.cicdecim(decf, diffd, numsecs);

% [EOF]
