function Hd = cic5
%CIC5 Returns a multirate filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the DSP System Toolbox 8.0.
%
% Generated on: 27-Dec-2014 17:43:03
%

decf    = 10;  % Decimation Factor
diffd   = 1;   % Differential Delay
numsecs = 5;   % Number of Sections

Hd = mfilt.cicdecim(decf, diffd, numsecs);

% [EOF]
