function Hd = cic_inv_sinc
%CIC_INV_SINC Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the DSP System Toolbox 8.0.
%
% Generated on: 03-Jan-2015 06:45:33
%

% FIR constrained equiripple Inverse Sinc Lowpass filter designed using
% the FIRCEQRIP function.

% All frequency values are in MHz.
Fs = 0.625;  % Sampling Frequency

N            = 20;               % Order
Fc           = 0.2;              % Cutoff Frequency
slope        = 0;                % Stopband Slope
isincffactor = 1;                % Inverse Sinc Frequency Factor
isincpower   = 6;                % Inverse Sinc Power
Dstop        = 0.0001;           % Stopband Attenuation
Dpass        = 0.0057563991496;  % Passband Ripple

% Calculate the coefficients using the FIRCEQRIP function.
b  = firceqrip(N, Fc/(Fs/2), [Dpass, Dstop], 'slope', slope, 'min', ...
               'invsinc', [isincffactor isincpower]);
Hd = dfilt.dffir(b);
set(Hd, 'Arithmetic', 'double');

% [EOF]
