function fir_da_generatehdl(filtobj)
%  FIR_DA_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 8.3 and the Filter Design HDL Coder 2.9.5.
%  Generated on: 2015-01-02 09:32:23
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  ResetType: Synchronous
%  FIRAdderStyle: tree
%  ResetInputPort: syn_rst
%  TargetDirectory: E:\百度云同步盘\书籍\书稿\第三章
%  Name: fir_da
%  RemoveResetFrom: ShiftRegister
%  DALUTPartition: 5
%  DARadix: 256
%  TargetLanguage: Verilog
%  TestBenchStimulus: impulse step ramp chirp noise 
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time FIR Filter (real)
%  -------------------------------
%  Filter Structure  : Direct-Form FIR
%  Filter Length     : 5
%  Stable            : Yes
%  Linear Phase      : Yes (Type 1)
%  Arithmetic        : fixed
%  Numerator         : s16,19 -> [-6.250000e-02 6.250000e-02)
%  Input             : s8,7 -> [-1 1)
%  Filter Internals  : Specify Precision
%    Output          : s8,7 -> [-1 1)
%    Product         : s31,31 -> [-5.000000e-01 5.000000e-01)
%    Accumulator     : s33,31 -> [-2 2)
%    Round Mode      : convergent
%    Overflow Mode   : wrap

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'ResetType', 'Synchronous',... 
               'FIRAdderStyle', 'tree',... 
               'ResetInputPort', 'syn_rst',... 
               'TargetDirectory', 'E:\百度云同步盘\书籍\书稿\第三章',... 
               'Name', 'fir_da',... 
               'RemoveResetFrom', 'ShiftRegister',... 
               'DALUTPartition', 5,... 
               'DARadix', 256,... 
               'TargetLanguage', 'Verilog',... 
               'TestBenchStimulus',  {'impulse', 'step', 'ramp', 'chirp', 'noise'},... 
               'GenerateHDLTestbench', 'on');

% [EOF]
