-- File generated by bch.exe program.
-- The constant package for BCH code (31,21), t=2
 -- with optimization= 1.
-- GF(2^5) is generated by polynomial [1+x+...] - 101001;
-- Constant necessary for decoder and encoder

PACKAGE   const IS
	CONSTANT m: INTEGER:= 5;
	CONSTANT n: INTEGER:= 31;  -- n= 2^m -1  -size of block
	CONSTANT k: INTEGER:= 21;  -- BCH code (n,k) -no. of information bits
	CONSTANT nk: INTEGER:= 10; -- nk=n-k
	CONSTANT t: INTEGER:= 2;  -- no. of errors to be corrected

	CONSTANT sizea: INTEGER:= 3; -- size of counter ca
	CONSTANT sizeb: INTEGER:= 3; -- size of counter cb 
		-- count = iteration* cb + ca
	CONSTANT sizel: INTEGER:= 3; 
		-- size of l integer (degree of error polynomial BMA)
END const;	

